kubernetes: kubernetes
pipelines:
  name: jfrog_demo_helm_deploy
  core:
    docker:
      name: jfrog_demo_core_docker
  helm:
    publish:
      name: jfrog_demo_helm_publish
helm:
  chart:
    namespace: jfrog-demo
    name: jfrog-demo
