artifactory: artifactory
kubernetes: kubernetes
pipelines:
  name: jfrog_demo_helm
  core:
    docker:
      name: jfrog_demo_core_docker
gitRepo:
  name: jfrog_demo_helm_gitrepo
  provider: github
  path: tsuyo/jfrog-demo-helm
  files:
    include: jfrog-demo-chart/.+
artifactoryRepo:
  deployer:
    name: demo-helm
helm:
  chart:
    namespace: jfrog-demo
    name: jfrog-demo
    version: 0.0.1
    path: ./jfrog-demo-chart
    valueFilePaths: helm-values.yaml
