replicaCount: 3
image:
  name: ${res_jfrog_demo_core_docker_image_imageName}
  tag: ${res_jfrog_demo_core_docker_image_imageTag}
  pullPolicy: Always
  port: 8080
  pullSecret: regcred
service:
  type: ClusterIP
  port: 80
ingress:
  host: jfrog-demo.dev.gcp.tsuyo.org
